  name: Deploy to github pages

  on:
    push:
      branches:
        - master

  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Setup Node.js version
          uses: actions/setup-node@v2.2.0
          with:
            node-version: '14.4.0'

        - name: Clean install dependencies
          run: npm ci

        - name: Build
          run: npm run build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
